apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deployment
  labels:
    app: cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - name: cloud-container
        image: salientcrossing/cloud
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 128Mi
