apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloud
build:
  artifacts:
    - image: salientcrossing/cloud
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
    - service.yaml
